---
abstract: 'web framework and templating system for small-medium sites.'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
  perl: 5.008
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS
provides:
  App::ZofCMS:
    file: lib/App/ZofCMS.pm
    version: 1.001004
  App::ZofCMS::Config:
    file: lib/App/ZofCMS/Config.pm
    version: 1.001004
  App::ZofCMS::Output:
    file: lib/App/ZofCMS/Output.pm
    version: 1.001004
  App::ZofCMS::Plugin:
    file: lib/App/ZofCMS/Plugin.pm
    version: 1.001004
  App::ZofCMS::Plugin::AccessDenied:
    file: lib/App/ZofCMS/Plugin/AccessDenied.pm
    version: 1.001004
  App::ZofCMS::Plugin::AntiSpamMailTo:
    file: lib/App/ZofCMS/Plugin/AntiSpamMailTo.pm
    version: 1.001004
  App::ZofCMS::Plugin::AutoDump:
    file: lib/App/ZofCMS/Plugin/AutoDump.pm
    version: 1.001004
  App::ZofCMS::Plugin::AutoEmptyQueryDelete:
    file: lib/App/ZofCMS/Plugin/AutoEmptyQueryDelete.pm
    version: 1.001004
  App::ZofCMS::Plugin::AutoIMGSize:
    file: lib/App/ZofCMS/Plugin/AutoIMGSize.pm
    version: 1.001004
  App::ZofCMS::Plugin::Barcode:
    file: lib/App/ZofCMS/Plugin/Barcode.pm
    version: 1.001004
  App::ZofCMS::Plugin::Base:
    file: lib/App/ZofCMS/Plugin/Base.pm
    version: 1.001004
  App::ZofCMS::Plugin::BasicLWP:
    file: lib/App/ZofCMS/Plugin/BasicLWP.pm
    version: 1.001004
  App::ZofCMS::Plugin::BoolSettingsManager:
    file: lib/App/ZofCMS/Plugin/BoolSettingsManager.pm
    version: 1.001004
  App::ZofCMS::Plugin::BreadCrumbs:
    file: lib/App/ZofCMS/Plugin/BreadCrumbs.pm
    version: 1.001004
  App::ZofCMS::Plugin::CRUD:
    file: lib/App/ZofCMS/Plugin/CRUD.pm
    version: 1.001004
  App::ZofCMS::Plugin::CSSMinifier:
    file: lib/App/ZofCMS/Plugin/CSSMinifier.pm
    version: 1.001004
  App::ZofCMS::Plugin::Comments:
    file: lib/App/ZofCMS/Plugin/Comments.pm
    version: 1.001004
  App::ZofCMS::Plugin::ConditionalRedirect:
    file: lib/App/ZofCMS/Plugin/ConditionalRedirect.pm
    version: 1.001004
  App::ZofCMS::Plugin::ConfigToTemplate:
    file: lib/App/ZofCMS/Plugin/ConfigToTemplate.pm
    version: 1.001004
  App::ZofCMS::Plugin::Cookies:
    file: lib/App/ZofCMS/Plugin/Cookies.pm
    version: 1.001004
  App::ZofCMS::Plugin::CurrentPageURI:
    file: lib/App/ZofCMS/Plugin/CurrentPageURI.pm
    version: 1.001004
  App::ZofCMS::Plugin::DBI:
    file: lib/App/ZofCMS/Plugin/DBI.pm
    version: 1.001004
  App::ZofCMS::Plugin::DBIPPT:
    file: lib/App/ZofCMS/Plugin/DBIPPT.pm
    version: 1.001004
  App::ZofCMS::Plugin::DataToExcel:
    file: lib/App/ZofCMS/Plugin/DataToExcel.pm
    version: 1.001004
  App::ZofCMS::Plugin::DateSelector:
    file: lib/App/ZofCMS/Plugin/DateSelector.pm
    version: 1.001004
  App::ZofCMS::Plugin::Debug::Dumper:
    file: lib/App/ZofCMS/Plugin/Debug/Dumper.pm
    version: 1.001004
  App::ZofCMS::Plugin::Debug::Validator::HTML:
    file: lib/App/ZofCMS/Plugin/Debug/Validator/HTML.pm
    version: 1.001004
  App::ZofCMS::Plugin::DirTreeBrowse:
    file: lib/App/ZofCMS/Plugin/DirTreeBrowse.pm
    version: 1.001004
  App::ZofCMS::Plugin::Doctypes:
    file: lib/App/ZofCMS/Plugin/Doctypes.pm
    version: 1.001004
  App::ZofCMS::Plugin::FeatureSuggestionBox:
    file: lib/App/ZofCMS/Plugin/FeatureSuggestionBox.pm
    version: 1.001004
  App::ZofCMS::Plugin::FileList:
    file: lib/App/ZofCMS/Plugin/FileList.pm
    version: 1.001004
  App::ZofCMS::Plugin::FileToTemplate:
    file: lib/App/ZofCMS/Plugin/FileToTemplate.pm
    version: 1.001004
  App::ZofCMS::Plugin::FileTypeIcon:
    file: lib/App/ZofCMS/Plugin/FileTypeIcon.pm
    version: 1.001004
  App::ZofCMS::Plugin::FileUpload:
    file: lib/App/ZofCMS/Plugin/FileUpload.pm
    version: 1.001004
  App::ZofCMS::Plugin::FloodControl:
    file: lib/App/ZofCMS/Plugin/FloodControl.pm
    version: 1.001004
  App::ZofCMS::Plugin::FormChecker:
    file: lib/App/ZofCMS/Plugin/FormChecker.pm
    version: 1.001004
  App::ZofCMS::Plugin::FormFiller:
    file: lib/App/ZofCMS/Plugin/FormFiller.pm
    version: 1.001004
  App::ZofCMS::Plugin::FormMailer:
    file: lib/App/ZofCMS/Plugin/FormMailer.pm
    version: 1.001004
  App::ZofCMS::Plugin::FormToDatabase:
    file: lib/App/ZofCMS/Plugin/FormToDatabase.pm
    version: 1.001004
  App::ZofCMS::Plugin::GetRemotePageTitle:
    file: lib/App/ZofCMS/Plugin/GetRemotePageTitle.pm
    version: 1.001004
  App::ZofCMS::Plugin::GoogleCalculator:
    file: lib/App/ZofCMS/Plugin/GoogleCalculator.pm
    version: 1.001004
  App::ZofCMS::Plugin::GooglePageRank:
    file: lib/App/ZofCMS/Plugin/GooglePageRank.pm
    version: 1.001004
  App::ZofCMS::Plugin::GoogleTime:
    file: lib/App/ZofCMS/Plugin/GoogleTime.pm
    version: 1.001004
  App::ZofCMS::Plugin::HTMLFactory::Entry:
    file: lib/App/ZofCMS/Plugin/HTMLFactory/Entry.pm
    version: 1.001004
  App::ZofCMS::Plugin::HTMLFactory::PageToBodyId:
    file: lib/App/ZofCMS/Plugin/HTMLFactory/PageToBodyId.pm
    version: 1.001004
  App::ZofCMS::Plugin::HTMLMailer:
    file: lib/App/ZofCMS/Plugin/HTMLMailer.pm
    version: 1.001004
  App::ZofCMS::Plugin::InstalledModuleChecker:
    file: lib/App/ZofCMS/Plugin/InstalledModuleChecker.pm
    version: 1.001004
  App::ZofCMS::Plugin::JavaScriptMinifier:
    file: lib/App/ZofCMS/Plugin/JavaScriptMinifier.pm
    version: 1.001004
  App::ZofCMS::Plugin::LinkifyText:
    file: lib/App/ZofCMS/Plugin/LinkifyText.pm
    version: 1.001004
  App::ZofCMS::Plugin::LinksToSpecs::CSS:
    file: lib/App/ZofCMS/Plugin/LinksToSpecs/CSS.pm
    version: 1.001004
  App::ZofCMS::Plugin::LinksToSpecs::HTML:
    file: lib/App/ZofCMS/Plugin/LinksToSpecs/HTML.pm
    version: 1.001004
  App::ZofCMS::Plugin::NavMaker:
    file: lib/App/ZofCMS/Plugin/NavMaker.pm
    version: 1.001004
  App::ZofCMS::Plugin::PreferentialOrder:
    file: lib/App/ZofCMS/Plugin/PreferentialOrder.pm
    version: 1.001004
  App::ZofCMS::Plugin::QueryToTemplate:
    file: lib/App/ZofCMS/Plugin/QueryToTemplate.pm
    version: 1.001004
  App::ZofCMS::Plugin::QuickNote:
    file: lib/App/ZofCMS/Plugin/QuickNote.pm
    version: 1.001004
  App::ZofCMS::Plugin::RandomBashOrgQuote:
    file: lib/App/ZofCMS/Plugin/RandomBashOrgQuote.pm
    version: 1.001004
  App::ZofCMS::Plugin::RandomPasswordGeneratorPurePerl:
    file: lib/App/ZofCMS/Plugin/RandomPasswordGeneratorPurePerl.pm
    version: 1.001004
  App::ZofCMS::Plugin::SendFile:
    file: lib/App/ZofCMS/Plugin/SendFile.pm
    version: 1.001004
  App::ZofCMS::Plugin::Session:
    file: lib/App/ZofCMS/Plugin/Session.pm
    version: 1.001004
  App::ZofCMS::Plugin::SplitPriceSelect:
    file: lib/App/ZofCMS/Plugin/SplitPriceSelect.pm
    version: 1.001004
  App::ZofCMS::Plugin::StartPage:
    file: lib/App/ZofCMS/Plugin/StartPage.pm
    version: 1.001004
  App::ZofCMS::Plugin::StyleSwitcher:
    file: lib/App/ZofCMS/Plugin/StyleSwitcher.pm
    version: 1.001004
  App::ZofCMS::Plugin::Sub:
    file: lib/App/ZofCMS/Plugin/Sub.pm
    version: 1.001004
  App::ZofCMS::Plugin::Syntax::Highlight::CSS:
    file: lib/App/ZofCMS/Plugin/Syntax/Highlight/CSS.pm
    version: 1.001004
  App::ZofCMS::Plugin::Syntax::Highlight::HTML:
    file: lib/App/ZofCMS/Plugin/Syntax/Highlight/HTML.pm
    version: 1.001004
  App::ZofCMS::Plugin::TOC:
    file: lib/App/ZofCMS/Plugin/TOC.pm
    version: 1.001004
  App::ZofCMS::Plugin::TagCloud:
    file: lib/App/ZofCMS/Plugin/TagCloud.pm
    version: 1.001004
  App::ZofCMS::Plugin::Tagged:
    file: lib/App/ZofCMS/Plugin/Tagged.pm
    version: 1.001004
  App::ZofCMS::Plugin::UserLogin:
    file: lib/App/ZofCMS/Plugin/UserLogin.pm
    version: 1.001004
  App::ZofCMS::Plugin::UserLogin::ChangePassword:
    file: lib/App/ZofCMS/Plugin/UserLogin/ChangePassword.pm
    version: 1.001004
  App::ZofCMS::Plugin::UserLogin::ForgotPassword:
    file: lib/App/ZofCMS/Plugin/UserLogin/ForgotPassword.pm
    version: 1.001004
  App::ZofCMS::Plugin::ValidationLinks:
    file: lib/App/ZofCMS/Plugin/ValidationLinks.pm
    version: 1.001004
  App::ZofCMS::Plugin::YouTube:
    file: lib/App/ZofCMS/Plugin/YouTube.pm
    version: 1.001004
  App::ZofCMS::Template:
    file: lib/App/ZofCMS/Template.pm
    version: 1.001004
  App::ZofCMS::Test::Plugin:
    file: lib/App/ZofCMS/Test/Plugin.pm
    version: 1.001004
requires:
  CGI: 0
  CSS::Minifier: 0
  Carp: 0
  Cwd: 0
  DBI: 0
  Data::Dumper: 0
  Data::Transformer: 0
  Digest::MD5: 0
  File::Copy: 0
  File::Find: 0
  File::Glob: 0
  File::Path: 0
  File::Spec: 0
  File::Spec::Functions: 0
  GD::Barcode: 0
  Getopt::Long: 0
  HTML::Entities: 0
  HTML::Template: 0
  Image::Size: 0
  JavaScript::Minifier: 0
  LWP::UserAgent: 0
  List::Util: 0
  MIME::Lite: 0
  MIME::Types: 0
  Mail::Send: 0
  Spreadsheet::DataToExcel: 0
  Storable: 0
  Syntax::Highlight::CSS: 0
  Syntax::Highlight::HTML: 0
  Test::Builder::Module: 0
  Time::Local: 0
  URI: 0
  URI::Escape: 0
  URI::Find::Schemeless: 0
  WWW::BashOrg: 0
  WWW::GetPageTitle: 0
  WWW::Google::Calculator: 0
  WWW::Google::PageRank: 0
  WWW::Google::Time: 0
  WebService::Validator::HTML::W3C: 0
  base: 0
  lib: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/zoffixznet/app-zofcms/issues
  homepage: http://metacpan.org/release/App-ZofCMS
  repository: git://github.com/zoffixznet/app-zofcms.git
version: 1.001004
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Author::ZOFFIX/OurPkgVersion'
      version: 0.005001
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 1
          check_all_prereqs: 1
          modules: []
          phase: release
          skip:
            - strict
            - warnings
            - base
            - ExtUtils::MakeMaker
            - IPC::Open3
            - File::Copy
      name: '@Author::ZOFFIX/PromptIfStale'
      version: 0.016
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::ZOFFIX/GatherDir'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::ZOFFIX/PruneCruft'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::ZOFFIX/ManifestSkip'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::ZOFFIX/MetaYAML'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::ZOFFIX/License'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::ZOFFIX/Readme'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::ZOFFIX/ExecDir'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::ZOFFIX/ShareDir'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::ZOFFIX/MakeMaker'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::ZOFFIX/Manifest'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::ZOFFIX/AutoPrereqs'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::ZOFFIX/MetaConfig'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Prereqs::AuthorDeps
      name: '@Author::ZOFFIX/Prereqs::AuthorDeps'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::ZOFFIX/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::ZOFFIX/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: 5.013
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: '@Author::ZOFFIX/MetaProvides::Package'
      version: 2.000001
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::ZOFFIX/GithubMeta'
      version: 0.42
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::ZOFFIX/InstallGuide'
      version: 1.200002
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::ZOFFIX/ReadmeAnyFromPod'
      version: 0.133360
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::ZOFFIX/Test::Compile'
      version: 2.039
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::ZOFFIX/Test::DistManifest'
      version: 2.000004
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: '@Author::ZOFFIX/Test::EOL'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Author::ZOFFIX/Test::Version'
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::ZOFFIX/MetaTests'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Author::ZOFFIX/Test::CPAN::Meta::JSON'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@Author::ZOFFIX/MojibakeTests'
      version: 0.5
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::ZOFFIX/NoTabsTests'
      version: 0.06
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::ZOFFIX/PodSyntaxTests'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::ZOFFIX/Test::CPAN::Changes'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::CheckSelfDependency
      config:
        Dist::Zilla::Plugin::CheckSelfDependency:
          finder:
            - ':InstallModules'
      name: '@Author::ZOFFIX/CheckSelfDependency'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::ZOFFIX/CheckPrereqsIndexed'
      version: 0.010
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::ZOFFIX/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::ZOFFIX/Git::NextVersion'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: '@Author::ZOFFIX/AutoMetaResources'
      version: 1.20
    -
      class: Dist::Zilla::Plugin::CopyFilesFromRelease
      name: '@Author::ZOFFIX/CopyFilesFromRelease'
      version: 0.001
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::ZOFFIX/TestRelease'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::ZOFFIX/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::ZOFFIX/ConfirmRelease'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::ZOFFIX/Git::Check'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::ZOFFIX/Git::Commit'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::ZOFFIX/Git::Tag'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::ZOFFIX/Git::Push'
      version: 2.020
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::ZOFFIX/UploadToCPAN'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::Pod::Spiffy
      name: Pod::Spiffy
      version: 1.001007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::ZOFFIX/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: 5.013
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.013
