---
abstract: 'web framework and templating system for small-medium sites.'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS
provides:
  App::ZofCMS:
    file: lib/App/ZofCMS.pm
    version: 0.0224
  App::ZofCMS::Config:
    file: lib/App/ZofCMS/Config.pm
    version: 0.0224
  App::ZofCMS::Output:
    file: lib/App/ZofCMS/Output.pm
    version: 0.0224
  App::ZofCMS::Template:
    file: lib/App/ZofCMS/Template.pm
    version: 0.0224
requires:
  CGI: 3.15
  CGI::Carp: 1.29
  Carp: 1.04
  File::Copy: 2.09
  File::Find: 1.12
  File::Path: 1.08
  File::Spec: 3.2701
  Getopt::Long: 2.35
  HTML::Template: 2.9
resources:
  license: http://dev.perl.org/licenses/
version: 0.0224
